// sorted with IDs
export const shapeLines = [
    '{"nOuter":3,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":3,"nInner":2,"lenOuter":{"x":"7.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"4.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"3","nInner":"2","lenOuter":{"x":"6.7","y":"5.2"},"lenInner":{"x":"4.2","y":"5.9"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"8.2","y":"5.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":"0.81"}',
    '{"nOuter":"6","nInner":2,"lenOuter":{"x":"6.9","y":"3"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"6","nInner":2,"lenOuter":{"x":"4.5","y":"3.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"3.2"},"lenInner":{"x":"2.2","y":"6.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"3.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"4.5"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.2","y":"4.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"3.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"3.2","y":2.2},"lenInner":{"x":"7.2","y":"2.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.4","y":"5.1"},"lenInner":{"x":"4.7","y":"2.6"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.3","y":"5.7"},"lenInner":{"x":"4.3","y":"2.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.3","y":"6.3"},"lenInner":{"x":"5.3","y":"0.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"0.302","y":"6.502"},"lenInner":{"x":"5.502","y":"0.002"},"offset":{"x":"7.5","y":"6.4"},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.2","y":"6.2"},"lenInner":{"x":5.2,"y":"0.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":4,"nInner":2,"lenOuter":{"x":"0.2","y":"1.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":"11.4","y":"0.2"},"offset":{"x":7,"y":7},"sceneScale":"0.63"}',
    '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"6","nInner":"3","lenOuter":{"x":"5.2","y":"0.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"4","nInner":"8","lenOuter":{"x":"4.2","y":"5.3"},"lenInner":{"x":"0.2","y":"5.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"16","nInner":"2","lenOuter":{"x":"4.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"18","nInner":2,"lenOuter":{"x":"5","y":"5.6"},"lenInner":{"x":"2.8","y":"6.1"},"offset":{"x":"7","y":"7"},"sceneScale":1}',
    '{"nOuter":"3","nInner":"8","lenOuter":{"x":"4.9","y":"5.7"},"lenInner":{"x":"7.8","y":"3"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"5","nInner":"6","lenOuter":{"x":"5.9","y":"4.6"},"lenInner":{"x":"2.3","y":"6.9"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"8","nInner":"8","lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":"4.2","y":"0.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"8","nInner":"8","lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":"4.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":4,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"4","nInner":"6","lenOuter":{"x":"4.2","y":"1.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":"5.4"},"offset":{"x":7,"y":"7.7"},"sceneScale":"1.34"}',
    '{"nOuter":"6","nInner":2,"lenOuter":{"x":"3.2","y":"3.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"11","nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"11","nInner":"5","lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"10","nInner":"6","lenOuter":{"x":"3.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":"11","nInner":"2","lenOuter":{"x":"5.2","y":"0.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',

    '{"nOuter":3,"nInner":2,"lenOuter":{"x":-1.9,"y":-1.9},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":5,"nInner":2,"lenOuter":{"x":0.7,"y":-1.9},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":4,"nInner":"2","lenOuter":{"x":1.9,"y":-2.5},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":30,"nInner":3,"lenOuter":{"x":-11.2,"y":-2.34},"lenInner":{"x":2.3,"y":6.9},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":4,"nInner":2,"lenOuter":{"x":-3.6,"y":1.8},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":2,"nInner":16,"lenOuter":{"x":-11.2,"y":-2.34},"lenInner":{"x":-1.9,"y":9.9},"offset":{"x":7,"y":7},"sceneScale":0.54}',
    '{"nOuter":8,"nInner":4,"lenOuter":{"x":-4.2,"y":-4.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":1}',
    '{"nOuter":6,"nInner":3,"lenOuter":{"x":-8.6,"y":6.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":0.75}',
    '{"nOuter":3,"nInner":3,"lenOuter":{"x":4.8,"y":4.8},"lenInner":{"x":0.1,"y":0.1},"offset":{"x":7,"y":7},"sceneScale":1.08}',
];

// original unsorted
// export const shapeLines = [
//     '{"nOuter":3,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":3,"nInner":2,"lenOuter":{"x":"7.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"3.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":4,"nInner":2,"lenOuter":{"x":"0.2","y":"1.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":4,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"6","nInner":2,"lenOuter":{"x":"3.2","y":"3.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"11","nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"11","nInner":"5","lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7}}',
    
//     '{"nOuter":"10","nInner":"6","lenOuter":{"x":"3.2","y":"0.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"3.2"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"8","nInner":"8","lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":"4.2","y":"0.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"8","nInner":"8","lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":"4.2","y":"4.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"4.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"6","nInner":"3","lenOuter":{"x":"5.2","y":"0.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.2","y":"4.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"3.2"},"lenInner":{"x":"2.2","y":"6.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"16","nInner":"2","lenOuter":{"x":"4.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"8.2","y":"5.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7},"sceneScale":"0.81"}',
    
//     '{"nOuter":"11","nInner":"2","lenOuter":{"x":"5.2","y":"0.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":2.2},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.2","y":"6.2"},"lenInner":{"x":5.2,"y":"0.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"4","nInner":"6","lenOuter":{"x":"4.2","y":"1.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"3.2","y":2.2},"lenInner":{"x":"7.2","y":"2.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"6.2","y":"6.2"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"6","nInner":2,"lenOuter":{"x":"4.5","y":"3.2"},"lenInner":{"x":"5.2","y":"5.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.3","y":"5.7"},"lenInner":{"x":"4.3","y":"2.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"4.3","y":"6.3"},"lenInner":{"x":"5.3","y":"0.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"2.4","y":"5.1"},"lenInner":{"x":"4.7","y":"2.6"},"offset":{"x":7,"y":7}}',
    
//     '{"nOuter":"8","nInner":2,"lenOuter":{"x":"6.2","y":"4.5"},"lenInner":{"x":"3.2","y":"4.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"4","nInner":"8","lenOuter":{"x":"4.2","y":"5.3"},"lenInner":{"x":"0.2","y":"5.2"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"3","nInner":"8","lenOuter":{"x":"4.9","y":"5.7"},"lenInner":{"x":"7.8","y":"3"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"3","nInner":"2","lenOuter":{"x":"6.7","y":"5.2"},"lenInner":{"x":"4.2","y":"5.9"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"5","nInner":"6","lenOuter":{"x":"5.9","y":"4.6"},"lenInner":{"x":"2.3","y":"6.9"},"offset":{"x":7,"y":7}}',
//     '{"nOuter":"18","nInner":2,"lenOuter":{"x":"5","y":"5.6"},"lenInner":{"x":"2.8","y":"6.1"},"offset":{"x":"7","y":"7"}}',
//     '{"nOuter":"6","nInner":2,"lenOuter":{"x":"6.9","y":"3"},"lenInner":{"x":5.2,"y":5.2},"offset":{"x":7,"y":7}}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":"11.4","y":"0.2"},"offset":{"x":7,"y":7},"sceneScale":"0.63"}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":2.2,"y":2.2},"lenInner":{"x":5.2,"y":"5.4"},"offset":{"x":7,"y":"7.7"},"sceneScale":"1.34"}',
//     '{"nOuter":5,"nInner":2,"lenOuter":{"x":"0.302","y":"6.502"},"lenInner":{"x":"5.502","y":"0.002"},"offset":{"x":"7.5","y":"6.4"},"sceneScale":1}',
// ];

// copied from Vue DevTools
// const shapeObjects = [
//     { nOuter: 3, nInner: 2, lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfaq', sceneScale: 1 },
//     { nOuter: 3, nInner: 2, lenOuter: { x: '7.2', y: '0.2' }, lenInner: { x: '3.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfar', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '6.2', y: '4.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfb4', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '4.2', y: '6.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfat', sceneScale: 1 },
//     { nOuter: '3', nInner: '2', lenOuter: { x: '6.7', y: '5.2' }, lenInner: { x: '4.2', y: '5.9' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbn', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '6.2', y: '6.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfbf', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '8.2', y: '5.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, sceneScale: '0.81', id: 'k9qxnfb9' },
//     { nOuter: '6', nInner: 2, lenOuter: { x: '6.9', y: '3' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfbq', sceneScale: 1 },
//     { nOuter: '6', nInner: 2, lenOuter: { x: '4.5', y: '3.2' }, lenInner: { x: '5.2', y: '5.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbg', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '6.2', y: '3.2' }, lenInner: { x: '2.2', y: '6.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfb7', sceneScale: 1 },
//     { nOuter: '8', nInner: 2, lenOuter: { x: '6.2', y: '3.2' }, lenInner: { x: '3.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfb1', sceneScale: 1 },
//     { nOuter: '8', nInner: 2, lenOuter: { x: '6.2', y: '4.5' }, lenInner: { x: '3.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbk', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '2.2', y: '4.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfb6', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '3.2', y: '6.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfas', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '6.2', y: 2.2 }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfbb', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '3.2', y: 2.2 }, lenInner: { x: '7.2', y: '2.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbe', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '2.4', y: '5.1' }, lenInner: { x: '4.7', y: '2.6' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbj', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '4.3', y: '5.7' }, lenInner: { x: '4.3', y: '2.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbh', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '4.3', y: '6.3' }, lenInner: { x: '5.3', y: '0.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbi', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '0.302', y: '6.502' }, lenInner: { x: '5.502', y: '0.002' }, offset: { x: '7.5', y: '6.4' }, sceneScale: 1, id: 'k9qxnfbt' },
//     { nOuter: 5, nInner: 2, lenOuter: { x: '2.2', y: '6.2' }, lenInner: { x: 5.2, y: '0.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbc', sceneScale: 1 },
//     { nOuter: 4, nInner: 2, lenOuter: { x: '0.2', y: '1.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfau', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: '11.4', y: '0.2' }, offset: { x: 7, y: 7 }, sceneScale: '0.63', id: 'k9qxnfbr' },
//     { nOuter: '8', nInner: 2, lenOuter: { x: '6.2', y: '0.2' }, lenInner: { x: '3.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfaz', sceneScale: 1 },
//     { nOuter: '6', nInner: '3', lenOuter: { x: '5.2', y: '0.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfb5', sceneScale: 1 },
//     { nOuter: '4', nInner: '8', lenOuter: { x: '4.2', y: '5.3' }, lenInner: { x: '0.2', y: '5.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbl', sceneScale: 1 },
//     { nOuter: '16', nInner: '2', lenOuter: { x: '4.2', y: '6.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfb8', sceneScale: 1 },
//     { nOuter: '18', nInner: 2, lenOuter: { x: '5', y: '5.6' }, lenInner: { x: '2.8', y: '6.1' }, offset: { x: '7', y: '7' }, id: 'k9qxnfbp', sceneScale: 1 },
//     { nOuter: '3', nInner: '8', lenOuter: { x: '4.9', y: '5.7' }, lenInner: { x: '7.8', y: '3' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbm', sceneScale: 1 },
//     { nOuter: '5', nInner: '6', lenOuter: { x: '5.9', y: '4.6' }, lenInner: { x: '2.3', y: '6.9' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbo', sceneScale: 1 },
//     { nOuter: '8', nInner: '8', lenOuter: { x: '6.2', y: '6.2' }, lenInner: { x: '4.2', y: '0.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfb2', sceneScale: 1 },
//     { nOuter: '8', nInner: '8', lenOuter: { x: '6.2', y: '6.2' }, lenInner: { x: '4.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfb3', sceneScale: 1 },
//     { nOuter: 4, nInner: 2, lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfav', sceneScale: 1 },
//     { nOuter: '4', nInner: '6', lenOuter: { x: '4.2', y: '1.2' }, lenInner: { x: '5.2', y: '5.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfbd', sceneScale: 1 },
//     { nOuter: 5, nInner: 2, lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: 5.2, y: '5.4' }, offset: { x: 7, y: '7.7' }, sceneScale: '1.34', id: 'k9qxnfbs' },
//     { nOuter: '6', nInner: 2, lenOuter: { x: '3.2', y: '3.2' }, lenInner: { x: '5.2', y: '5.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfaw', sceneScale: 1 },
//     { nOuter: '11', nInner: 2, lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfax', sceneScale: 1 },
//     { nOuter: '11', nInner: '5', lenOuter: { x: 2.2, y: 2.2 }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfay', sceneScale: 1 },
//     { nOuter: '10', nInner: '6', lenOuter: { x: '3.2', y: '0.2' }, lenInner: { x: '3.2', y: '4.2' }, offset: { x: 7, y: 7 }, id: 'k9qxnfb0', sceneScale: 1 },
//     { nOuter: '11', nInner: '2', lenOuter: { x: '5.2', y: '0.2' }, lenInner: { x: 5.2, y: 5.2 }, offset: { x: 7, y: 7 }, id: 'k9qxnfba', sceneScale: 1 }
// ];
// (function print() {
//     let s = shapeObjects.map(_ => {
//         return `'${JSON.stringify(_)}'`;
//     }).join(',\n');
//     s = `[\n${s}\n]`;
//     console.log(s);
// })();

